CREATE DATABASE IF NOT EXISTS bb;
USE bb;

CREATE TABLE users (
  userId INT(5) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE expenses (
  expenseId INT(5) AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(50) NOT NULL,
  date DATE NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  userId INT(5) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_user_expenses FOREIGN KEY(userId) REFERENCES users(userId)
);